# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
VAGRANT_BOX_URL   = "https://github.com/CommanderK5/packer-centos-template/releases/download/0.7.2/vagrant-centos-7.2.box"
VAGRANT_BOX_NAME  = "centos-72"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = VAGRANT_BOX_NAME
  config.vm.box_url = VAGRANT_BOX_URL
  config.vm.boot_timeout = 600
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.synced_folder "../../weekly_report-master", "/home/vagrant/synced_weekly_report"
  config.vm.provision "shell", :path => "initialize_root.sh"
  config.vm.provision "shell", :path => "initialize.sh", :privileged => false
end
